config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :articles do
    resources :comments, only: :create do
      patch :approve, on: :member
    end
  end
  resources :projects
  root 'static_pages#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  has_many :comments

  def owned_by?(user)
    author_id == user.id
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :body, presence: true

  def unapproved?
    !approved
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true, length: { in: 4..255 }
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles, foreign_key: 'author_id'

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.nickname
      user.email = "#{user.name}-CHANGEME@twitter.example.com"
    end
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new(session['devise.user_attributes'], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def author?
    role == 'author'
  end

  def editor?
    role == 'editor'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:error] = 'You are not authorized to perform this action'
    redirect_to request.referrer || root_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_scoped_article, except: [:index, :new, :create]
  after_action :verify_authorized, except: [:index, :show]
  after_action :verify_policy_scoped, except: [:new, :create]

  def index
    @articles = policy_scope(Article)
  end

  def show
    @comments = Pundit.policy_scope(current_user, @article.comments)
    @comment = Comment.new
  end

  def new
    @article = Article.new
    authorize @article
  end

  def edit
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    authorize @article
    if @article.save
      current_user.articles << @article
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @article
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @article
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_scoped_article
    @article = policy_scope(Article).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow
  # the white list through.
  def article_params
    params.require(:article).permit(
      *policy(@article || Article).permitted_attributes)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def create
    @article = Pundit.policy_scope(current_user, Article).find(
      params[:article_id])
    @comment = @article.comments.build(comment_params)
    if @comment.save
      flash[:notice] = 'Thank you for commenting. Your comment has
        been received and is awaiting review.'
    else
      flash[:alert] = 'Invalid comment. Please revise and resubmit.'
    end
    redirect_to @article
  end

  def approve
    @article = Pundit.policy_scope(current_user, Article).find(
      params[:article_id])
    @comment = policy_scope(@article.comments).find(params[:id])
    authorize @comment
    @comment.update(approved: true)
    redirect_to @article
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env['omniauth.auth'])
    if user.persisted?
      flash.notice = "#{user.name}, you are signed in!"
      sign_in_and_redirect user, notice: "#{user.name}, you are signed in"
    else
      session['devise.user_attributes'] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = 'Project has been created'
      redirect_to @project
    else
      flash.now[:error] = 'Project could not be saved'
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      flash[:success] = 'Project has been updated'
      redirect_to @project
    else
      flash.now[:error] = 'Project could not be updated'
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project has been deleted'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then 'info'
    when 'success' then 'success'
    when 'error' then 'alert'
    when 'alert' then 'warning'
    end
  end
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/articles/_comment_form.html.erb
<%= form_for [@article, @comment] do |f| %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit Comment' %>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <% if policy(@article).publish? %>
    <div class="row collapse">
      <div class="small-3 columns">
        <%= f.label :published, class: 'right inline',
         title: 'Is this article published?', data: { tooltip: true } %><br>
      </div>
      <div class="small-9 columns">
        <%= f.check_box :published %>
      </div>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article %></td>
        <% if policy(article).edit? %>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <% end %>
        <% if policy(article).destroy? %>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path if user_signed_in? %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p id="author">
  <b>By: </b>
  <%= @article.author.email %>
</p>
<p id="status">
  <b>Status: </b>
  <%= @article.published? ? "Published" : "Unpublished" %>
</p>


<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<% if policy(@article).edit? %>
  <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<% if policy(@article).destroy? %>
  <%= link_to 'Destroy', article_path(@article), method: :delete,
    data: { confirm: "Are you sure?" } %>
<% end %>

<h3>Comments</h3>

<%= render partial: 'comments/comment',
  collection: @comments,
  spacer_template: 'comments/spacer' ||
  "No comments have submitted for this article yet" %>

<h4>Leave us a comment!</h4>

<%= render 'comments/form' %>

<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<div class="comment">
  <p>--> <%= comment.body %></p>
  <div class="row">
    <div class="columns small-1">
      <% if policy(comment).approve? && comment.unapproved? %>
        <%= link_to 'Approve',
        approve_article_comment_path(@article, comment),
        method: :patch %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@article, @comment] do |f| %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit Comment' %>
  </div>
<% end %>

app/views/comments/_spacer.html.erb
<p>###############################</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= flash_class(name) %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class='top-bar' data-topbar>
  <ul class='title-area'>
    <li class='name'><%= link_to 'Home', root_path %></li>
    <li class='toggle-topbar menu-icon'><a href='#'>Menu</a></li>
  </ul>
  <div class='top-bar-section'>
    <ul class='right'>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class="divider"></li>
<li><%= link_to 'Bio', '#' %></li>
<li class="divider"></li>
<li><%= link_to 'Projects', '#' %></li>
<li class="divider"></li>

<% if user_signed_in? %>
  <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete,
    data: { confirm: 'Are you sure?' } %></li>
<% else %>
  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'Log In', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Portfolio" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Portfolio" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, 'error') %> prevented
        this record from being saved</h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

<%= link_to 'Cancel', :back %>

app/views/projects/index.html.erb
<h2>My Portfolio</h2>

<% @projects.each do |project| %>
  <div class="project", id="<%= dom_id(project) %>">
    <h3><%= project.name %></h3>
    <p><%= project.description %></p>
    <div class="nav"%>
      <%= link_to 'Show', project %>
      <%= link_to 'Edit', edit_project_path(project) %>
      <%= link_to 'Delete', project, method: 'delete',
        data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

<br />
<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<%= image_tag "#{@project.image_url}" %>
<p><%= @project.description %></p>

<%= link_to 'Back', :back %>
<%= link_to 'Delete', project_path(@project), method: 'delete',
    data: { confirm: 'Are you sure?' } %>

app/views/static_pages/_projects.html.erb
<h2 class='text-center'>Projects</h2>
<div class='row'>
  <div class='columns small-4'>
    <h3 class='text-center'>Sample Project</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class='columns small-4'>
    <h3 class='text-center'>Sample Project</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class='columns small-4'>
    <h3 class='text-center'>Sample Project</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class='columns small-4'>
    <h3 class='text-center'>Sample Project</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class='columns small-4'>
    <h3 class='text-center'>Sample Project</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>